id: P7AA4A353
initial_creation_type: input
source_metadata:
  Title: Tattvaratn훮val카
  Editor: H. UI
  Publisher: '-'
  Place of Publication: '-'
  Year: '1963'
  Tattvaratn훮val카:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:11:43.687314'
last_modified_at: '2022-03-08T17:11:43.687322'
